name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-rust:
    name: Rust check
    runs-on: ubuntu-latest
    env:
      PYO3_USE_ABI3_FORWARD_COMPATIBILITY: "1"
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install Rust stable
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          toolchain: stable
          components: clippy

      - name: Cache Rust dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rust/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('rust/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: cargo check
        run: cargo check --manifest-path rust/Cargo.toml

      - name: clippy
        run: cargo clippy --manifest-path rust/Cargo.toml -- -D warnings
